require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/court_types", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # CourtType. As you add validations to CourtType, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      CourtType.create! valid_attributes
      get court_types_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      court_type = CourtType.create! valid_attributes
      get court_type_url(court_type)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_court_type_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      court_type = CourtType.create! valid_attributes
      get edit_court_type_url(court_type)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new CourtType" do
        expect {
          post court_types_url, params: { court_type: valid_attributes }
        }.to change(CourtType, :count).by(1)
      end

      it "redirects to the created court_type" do
        post court_types_url, params: { court_type: valid_attributes }
        expect(response).to redirect_to(court_type_url(CourtType.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new CourtType" do
        expect {
          post court_types_url, params: { court_type: invalid_attributes }
        }.to change(CourtType, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post court_types_url, params: { court_type: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested court_type" do
        court_type = CourtType.create! valid_attributes
        patch court_type_url(court_type), params: { court_type: new_attributes }
        court_type.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the court_type" do
        court_type = CourtType.create! valid_attributes
        patch court_type_url(court_type), params: { court_type: new_attributes }
        court_type.reload
        expect(response).to redirect_to(court_type_url(court_type))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        court_type = CourtType.create! valid_attributes
        patch court_type_url(court_type), params: { court_type: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested court_type" do
      court_type = CourtType.create! valid_attributes
      expect {
        delete court_type_url(court_type)
      }.to change(CourtType, :count).by(-1)
    end

    it "redirects to the court_types list" do
      court_type = CourtType.create! valid_attributes
      delete court_type_url(court_type)
      expect(response).to redirect_to(court_types_url)
    end
  end
end
